const data = [
    {"title": "JOOLA Ben Johns Perseus CFS 16", "img": "https://cdn11.bigcommerce.com/s-tl5mxjzfsl/images/stencil/960w/products/4742/26604/JOOLA-Ben-Johns-Perseus-CFS-16-Pickleball-Paddle-2__16408.1699484406.jpg?c=1", "bestPrice": "249.95", "brand": "JOOLA", "color": ["Black"], "surface": "Carbon Fiber", "playStyle": "Control", "coreThickness": [16], "handleLength": 5.5, "paddleWeight": [8.5], "paddleShape": "Elongated", "aff_links": [{"retailer": "Pickleball Central", "link": "https://pickleballcentral.com/joola-ben-johns-perseus-cfs-16-carbon-fiber-pickleball-paddle"},{"retailer": "Amazon", "link": "https://www.amazon.com/JOOLA-Perseus-Pickleball-Technology-Increased/dp/B0C4M4X7RD?th=1"}]}, 
    {"title": "Selkirk Vanguard Power Air Invikta", "img": "https://cdn11.bigcommerce.com/s-tl5mxjzfsl/products/1988/images/24099/SEL1146_CatherineParenteauSignature_01_1000__48974.1696980644.386.513.jpg?c=1", "bestPrice": "249.99", "brand": "Selkirk", "color": ["Blue"], "surface": "Fiberglass/Carbon Fiber", "playStyle": "Balanced", "coreThickness": [12.7], "handleLength": 5.25, "paddleWeight": [7.9], "paddleShape": "Elongated", "aff_links": [{"retailer": "Pickleball Central", "link": "https://pickleballcentral.com/selkirk-vanguard-power-air-invikta-paddle"}]}, 
    {"title": "CRBN 2X Power Series", "img": "https://cdn11.bigcommerce.com/s-tl5mxjzfsl/products/4390/images/24063/CRBN-2X-Pickleball-Paddle-5__39189.1696883811.386.513.jpg?c=1", "bestPrice": "229.99", "brand": "CRBN", "color": ["Black"], "surface": "Carbon Fiber", "playStyle": "Power", "coreThickness": [14,16], "handleLength": 5, "paddleWeight": [8.0], "paddleShape": "Square", "aff_links": [{"retailer": "Pickleball Central", "link": "https://pickleballcentral.com/crbn-2x-power-series-carbon-fiber-paddle"}]}, 
    {"title": "ProKennex Kinetic Black Ace Pro", "img": "https://cdn11.bigcommerce.com/s-tl5mxjzfsl/products/4350/images/17628/PKX405_KineticBlackAcePro_1_1000__13951.1669839542.386.513.jpg?c=1", "bestPrice": "250.00", "brand": "ProKennex", "color": ["Black","Red"], "surface": "Carbon Fiber", "playStyle": "Balanced", "coreThickness": [11], "handleLength": 5.3, "paddleWeight": [7.94], "paddleShape": "Square", "aff_links": [{"retailer": "Pickleball Central", "link": "https://pickleballcentral.com/prokennex-kinetic-black-ace-pro-pickleball-paddle"}]}, 
    {"title": "CRBN 2", "img": "https://cdn11.bigcommerce.com/s-tl5mxjzfsl/products/2515/images/24037/CRB102_CRBN2_14mm_1_1000_2__80867.1696879334.386.513.jpg?c=1", "bestPrice": "179.99", "brand": "CRBN", "color": ["Black","White"], "surface": "Carbon Fiber", "playStyle": "Control", "coreThickness": [13,14,16], "handleLength": 4.75, "paddleWeight": [7.9], "paddleShape": "Square", "aff_links": [{"retailer": "Pickleball Central", "link": "https://pickleballcentral.com/crbn-2-carbon-fiber-paddle"}]}, 
    {"title": "Vatic Pro Prism Flash", "img": "https://vaticpro.com/cdn/shop/files/DSC03090.jpg?v=1685062975&width=1200", "bestPrice": "99.99", "brand": "Vatic Pro", "color": ["Black"], "surface": "Carbon Fiber", "playStyle": "Control", "coreThickness": [14,16], "handleLength": 5.3, "paddleWeight": [7.8,8.1], "paddleShape": "Standard", "aff_links": [{"retailer": "Vatic Pro", "link": "https://vaticpro.com/products/prism-flash-16mm"}]}, 
    {"title": "Engage Pursuit Pro EX 6.0 ", "img": "https://cdn11.bigcommerce.com/s-tl5mxjzfsl/products/4919/images/24551/Engage-Pursuit-Pro-EX-6.0-Pickleball-Paddle__61458.1697486734.386.513.jpg?c=1", "bestPrice": "259.99", "brand": "Engage", "color": ["Black"], "surface": "Carbon Fiber", "playStyle": "Control", "coreThickness": [16], "handleLength": 5, "paddleWeight": [8.25], "paddleShape": "Square", "aff_links": [{"retailer": "Pickleball Central", "link": "https://pickleballcentral.com/engage-pursuit-pro-ex-6-0-carbon-fiber-pickleball-paddle/"}]}, 
    {"title": "Electrum Model E Elite 16mm ", "img": "https://cdn11.bigcommerce.com/s-tl5mxjzfsl/products/4702/images/24378/Electrum-Model-E-Elite-Paddle-2__05915.1697220621.386.513.jpg?c=1", "bestPrice": "199.99", "brand": "Electrum", "color": ["Blue"], "surface": "Carbon Fiber", "playStyle": "Balanced", "coreThickness": [16], "handleLength": 5.25, "paddleWeight": [8.3], "paddleShape": "Elongated", "aff_links": [{"retailer": "Pickleball Central", "link": "https://pickleballcentral.com/electrum-model-e-elite-16mm-carbon-fiber-pickleball-paddle"}]}, 
    {"title": "Electrum Pro II ", "img": "https://cdn11.bigcommerce.com/s-tl5mxjzfsl/products/1496/images/24349/Electrum-Pro-II-Pickleball-Paddle-2__56507.1697219213.386.513.jpg?c=1", "bestPrice": "149.99", "brand": "Electrum", "color": ["Black/Gold"], "surface": "Graphite", "playStyle": "Control", "coreThickness": [11], "handleLength": 5.25, "paddleWeight": [8.0], "paddleShape": "Square", "aff_links": [{"retailer": "Pickleball Central", "link": "https://pickleballcentral.com/electrum-pro-ii-graphite-pickleball-paddle"}]}, 
    {"title": "Volair Mach 1 Forza ", "img": "https://cdn11.bigcommerce.com/s-tl5mxjzfsl/products/4868/images/22212/VOL101_ForzaPaddle_14mm_1_1000__77020.1691788956.386.513.jpg?c=1", "bestPrice": "179.99", "brand": "Volair", "color": ["Black/Blue"], "surface": "Carbon Fiber", "playStyle": "Balanced", "coreThickness": [14,16], "handleLength": 5.5, "paddleWeight": [8.0,8.2], "paddleShape": "Standard", "aff_links": [{"retailer": "Pickleball Central", "link": "https://pickleballcentral.com/volair-mach-1-forza-carbon-fiber-pickleball-paddle"}]},
    {"title": "Engage Pursuit Pro MX ", "img": "https://cdn11.bigcommerce.com/s-tl5mxjzfsl/products/4918/images/24553/Engage-Pursuit-Pro-MX-Pickleball-Paddle__33534.1697487256.386.513.jpg?c=1", "bestPrice": "259.99", "brand": "Engage", "color": ["Black"], "surface": "Carbon Fiber", "playStyle": "Balanced", "coreThickness": [13], "handleLength": 5.75, "paddleWeight": [8.15], "paddleShape": "Elongated", "aff_links": [{"retailer": "Pickleball Central", "link": "https://pickleballcentral.com/engage-pursuit-pro-mx-carbon-fiber-pickleball-paddle"}]}, 
    {"title": "Gearbox Pro Power Elongated", "img": "https://cdn11.bigcommerce.com/s-tl5mxjzfsl/images/stencil/1000x1000/products/4980/25305/Gearbox-PRO-Power-Elongated-Pickleball-Paddle-1__71089.1698265563.jpg?c=1", "bestPrice": "274.99", "brand": "Gearbox", "color": ["Black"], "surface": "Carbon Fiber", "playStyle": "Power", "coreThickness": [14], "handleLength": 5.5, "paddleWeight": [8.0], "paddleShape": "Elongated", "aff_links": [{"retailer": "Pickleball Central", "link": "https://pickleballcentral.com/gearbox-pro-power-elongated-carbon-fiber-pickleball-paddle/"}]},
    {"title": "Gearbox Pro Control Elongated", "img": "https://cdn11.bigcommerce.com/s-tl5mxjzfsl/images/stencil/1000x1000/products/4982/25315/Gearbox-Pro-Control-Elongated-Paddle-1__37407.1698266040.jpg?c=1", "bestPrice": "274.99", "brand": "Gearbox", "color": ["Black"], "surface": "Carbon Fiber", "playStyle": "Control", "coreThickness": [14], "handleLength": 5.5, "paddleWeight": [8.0], "paddleShape": "Elongated", "aff_links": [{"retailer": "Pickleball Central", "link": "https://pickleballcentral.com/gearbox-pro-control-elongated-carbon-fiber-pickleball-paddle/"}]},
    {"title": "Six Zero Double Black Diamond", "img": "https://www.sixzeropickleball.com/cdn/shop/files/1-14mm-DBD-Whitelogo.png?v=1698897884&width=1800", "bestPrice": "180", "brand": "Six Zero", "color": ["Black"], "surface": "Carbon Fiber", "playStyle": "Control", "coreThickness": [14,16], "handleLength": 5.5, "paddleWeight": [8.1], "paddleShape": "Standard", "aff_links": [{"retailer": "Six Zero", "link": "https://www.sixzeropickleball.com/products/double-black-diamond"}]},
    
];

export default data;